version: '3.8'

services:
  db:
    image: postgres:15 # Use a specific PostgreSQL version (e.g., 15)
    container_name: creatorflow-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password # CHANGE THIS FOR PRODUCTION!
      POSTGRES_DB: creatorflow_db
    ports:
      - "5432:5432" # Map host port 5432 to container port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data in a volume

volumes:
  postgres_data: # Define the named volume 